=== j5int/uct-maths-competition/desktop-app/Schools.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:od="urn:schemas-microsoft-com:officedata">
<xsd:element name="dataroot">
<xsd:complexType>
<xsd:sequence>
<xsd:element ref="Schools" minOccurs="0" maxOccurs="unbounded"/>
</xsd:sequence>
<xsd:attribute name="generated" type="xsd:dateTime"/>
</xsd:complexType>
</xsd:element>
<xsd:element name="Schools">
<xsd:annotation>
<xsd:appinfo>
<od:tableProperty name="OrderByOn" type="1" value="1"/>
<od:tableProperty name="Orientation" type="2" value="0"/>
<od:tableProperty name="DefaultView" type="2" value="2"/>
<od:tableProperty name="GUID" type="9" value="WQgoih/qDU6FFTgSo3pk1A==
"/>
<od:tableProperty name="DisplayViewsOnSharePointSite" type="2" value="1"/>
<od:tableProperty name="TotalsRow" type="1" value="0"/>
<od:tableProperty name="FilterOnLoad" type="1" value="0"/>
<od:tableProperty name="OrderByOnLoad" type="1" value="1"/>
<od:tableProperty name="HideNewField" type="1" value="0"/>
<od:tableProperty name="BackTint" type="6" value="100"/>
<od:tableProperty name="BackShade" type="6" value="100"/>
<od:tableProperty name="ThemeFontIndex" type="4" value="-1"/>
<od:tableProperty name="AlternateBackThemeColorIndex" type="4" value="-1"/>
<od:tableProperty name="AlternateBackTint" type="6" value="100"/>
<od:tableProperty name="AlternateBackShade" type="6" value="100"/>
<od:tableProperty name="DatasheetGridlinesThemeColorIndex" type="4" value="-1"/>
<od:tableProperty name="DatasheetForeThemeColorIndex" type="4" value="-1"/>
<od:tableProperty name="OrderBy" type="12" value="[Schools].[Name], [Schools].[Key], [Schools].[Language], [Schools].[Address], [Schools].[Phone], [Schools].[Fax], [Schools].[Contact], [Schools].[Entered], [Schools].[Score], [Schools].[Email]"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:complexType>
<xsd:sequence>
<xsd:element name="Name" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="2970"/>
<od:fieldProperty name="ColumnOrder" type="3" value="1"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="AllowZeroLength" type="1" value="1"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="255"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="Key" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="525"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="AllowZeroLength" type="1" value="1"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="255"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="Language" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="750"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="AllowZeroLength" type="1" value="1"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="255"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="Address" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="2280"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="AllowZeroLength" type="1" value="1"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="255"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="Phone" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="AllowZeroLength" type="1" value="1"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="255"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="Fax" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="1350"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="AllowZeroLength" type="1" value="1"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="255"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="Contact" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="855"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="AllowZeroLength" type="1" value="1"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="255"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="Entered" minOccurs="1" od:jetType="yesno" od:sqlSType="bit" od:nonNullable="yes" type="xsd:boolean">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="735"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="Score" minOccurs="0" od:jetType="longinteger" od:sqlSType="int" type="xsd:int">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="570"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="DecimalPlaces" type="2" value="255"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="Email" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="3570"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="AllowZeroLength" type="1" value="1"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="50"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
</xsd:sequence>
</xsd:complexType>
</xsd:element>
</xsd:schema>

=== j5int/uct-maths-competition/web-app/EntryForm/Schools.xml
<?xml version="1.0" encoding="UTF-8"?>
<dataroot xmlns:od="urn:schemas-microsoft-com:officedata" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"  xsi:noNamespaceSchemaLocation="Schools.xsd" generated="2012-03-09T09:52:46">
<Schools>
<Name>Abbott&amp;#039s Coll. Claremont</Name>
<Key>002</Key>
<Language>e</Language>
<Address>P O Box 2317
CLAREINCH
7740</Address>
<Phone>021 671-1173</Phone>
<Fax>021 671-2630</Fax>
<Contact></Contact>
<Entered>1</Entered>
<Score>0</Score>
<Email>bjacoby@abbotts.co.za</Email>
</Schools>
<Schools>
<Name>Abbott&amp;#039s Coll. Milnerton</Name>
<Key>003</Key>
<Language>e</Language>
<Address>8 Eddison Way
Century Gate
Century Cit
7441</Address>
<Phone>021 551 4090</Phone>
<Fax>021 551 4093</Fax>
<Contact></Contact>
<Entered>0</Entered>
<Score>0</Score>
<Email>kate@abbottsm.wcape.school.za</Email>
</Schools>
<Schools>
<Name>Alexander Sinton High</Name>
<Key>004</Key>
<Language>e</Language>
<Address>Thornton Road
Crawford
7764</Address>
<Phone>021 697 1350</Phone>
<Fax>021 696 1756</Fax>
<Contact></Contact>
<Entered>0</Entered>
<Score>0</Score>
<Email></Email>
</Schools>
<Schools>
<Name>Arcadia Sec. School</Name>
<Key>005</Key>
<Language>e</Language>
<Address>03 Karee Road
BONTEHEUWEL
7764</Address>
<Phone>021 694 9941</Phone>
<Fax>021 694 1736</Fax>
<Contact></Contact>
<Entered>0</Entered>
<Score>0</Score>
<Email></Email>
</Schools>
<Schools>
<Name>Athlone High School</Name>
<Key>006</Key>
<Language>e</Language>
<Address>Calendula Road
SILVERTOWN
0184</Address>
<Phone>021 637 6930</Phone>
<Fax>021 637 4151</Fax>
<Contact></Contact>
<Entered>0</Entered>
<Score>0</Score>
<Email></Email>
</Schools>
<Schools>
<Name>Atlantis Sek. Skool</Name>
<Key>007</Key>
<Language>a</Language>
<Address>P O Box 3019
Atlantis
7349</Address>
<Phone>021 572 3330</Phone>
<Fax>021 572 7963</Fax>
<Contact></Contact>
<Entered>1</Entered>
<Score>0</Score>
<Email>admin@atlantissec.wcape.school.za</Email>
</Schools>
<Schools>
<Name>Belgravia High School</Name>
<Key>009</Key>
<Language>e</Language>
<Address>Veld Road
BELGRAVIA ESTATE
7764
</Address>
<Phone>021 696 5188</Phone>
<Fax>021 697 0370</Fax>
<Contact></Contact>
<Entered>0</Entered>
<Score>0</Score>
<Email>admin@belgravia.wcape.school.za</Email>
</Schools>
<Schools>
<Name>Bellville South S. School</Name>
<Key>010</Key>
<Language>e</Language>
<Address>P O Box 367
KASSELSVLEI
BELLVILLE SOUTH
7533</Address>
<Phone> 021 951 6600</Phone>
<Fax>021 951 5270</Fax>
<Contact></Contact>
<Entered>0</Entered>
<Score>0</Score>
<Email>postmaster@bellvillesouthsss.wcape.school.za</Email>
</Schools>
<Schools>
<Name>Bellville H S</Name>
<Key>011</Key>
<Language>e</Language>
<Address>De La Haye Laan
BELLVILLE
7530</Address>
<Phone>021 948 4140</Phone>
<Fax>021 948 1801</Fax>
<Contact></Contact>
<Entered>0</Entered>
<Score>0</Score>
<Email>general@bellvillehigh.co.za</Email>
</Schools>
<Schools>
<Name>Bellville Technical H S</Name>
<Key>012</Key>
<Language>e</Language>
<Address>Private Bag X4
SANLAMHOF
7532</Address>
<Phone>021 948 6951</Phone>
<Fax>021 946 3752</Fax>
<Contact></Contact>
<Entered>0</Entered>
<Score>0</Score>
<Email></Email>
</Schools>
<Schools>
<Name>Bergvliet High School</Name>
<Key>013</Key>
<Language>e</Language>
<Address>Firgrove Way
BERGVLIET
7945</Address>
<Phone>021 712 0284</Phone>
<Fax>021 715 0631</Fax>
<Contact></Contact>
<Entered>0</Entered>
<Score>0</Score>
<Email>jenny@bhs.wcape.school.co.za</Email>
</Schools>
<Schools>
<Name>Bloemhof H Meisiesskool</Name>
<Key>014</Key>
<Language>a</Language>
<Address>Posbus 188
STELLENBOSCH
7599</Address>
<Phone> 021 887 3067</Phone>
<Fax>021 887 3044</Fax>
<Contact></Contact>
<Entered>0</Entered>
<Score>0</Score>
<Email></Email>
</Schools>
<Schools>
<Name>Boland Landbouskool </Name>
<Key>015</Key>
<Language>a</Language>
<Address>Privaatsak X01
WINDMEUL
7630</Address>
<Phone>021 869-8143</Phone>
<Fax>021869-8144</Fax>
<Contact></Contact>
<Entered>1</Entered>
<Score>0</Score>
<Email>hlb@mweb.co.za</Email>
</Schools>
<Schools>
<Name>Bredasdorp H S</Name>
<Key>016</Key>
<Language>a</Language>
<Address>Posbus 255
BREDASDORP
7280</Address>
<Phone>028 424 2207</Phone>
<Fax>028 424 1210</Fax>
<Contact></Contact>
<Entered>0</Entered>
<Score>0</Score>
<Email>brdhighadm@brd.dorea.co.za</Email>
</Schools>
<Schools>
<Name>Bridge House School</Name>
<Key>017</Key>
<Language>e</Language>
<Address>P O Box 444
FRANSCHHOEK
7690</Address>
<Phone>021 874-1790</Phone>
<Fax>021 874-1923</Fax>
<Contact></Contact>
<Entered>1</Entered>
<Score>0</Score>
<Email>alaadl@bridgehouse.org.za</Email>
</Schools>
<Schools>
<Name>Buren Hoerskool</Name>
<Key>018</Key>
<Language>e</Language>
<Address>Poole Street
YSTERPLAAT
7405</Address>
<Phone>021 511-1912</Phone>
<Fax>021 510 8206</Fax>
<Contact></Contact>
<Entered>0</Entered>
<Score>0</Score>
<Email>mwbhs@mweb.co.za</Email>
</Schools>
<Schools>
<Name>Camps Bay High School</Name>
<Key>019</Key>
<Language>e</Language>
<Address>Lower Kloof Road
CAMPS BAY
8005</Address>
<Phone>021 438 1507</Phone>
<Fax>021 438 5912</Fax>
<Contact></Contact>
<Entered>0</Entered>
<Score>0</Score>
<Email></Email>
</Schools>
<Schools>
<Name>Cathkin High School</Name>
<Key>020</Key>
<Language>e</Language>
<Address>5th Street
HEIDEVELD
7764</Address>
<Phone>021 637 5366</Phone>
<Fax>021 633 2701</Fax>
<Contact></Contact>
<Entered>0</Entered>
<Score>0</Score>
<Email></Email>
</Schools>
<Schools>
<Name>Ned Doman H S</Name>
<Key>075</Key>
<Language>e</Language>
<Address>Buckley Avenue
ATHLONE
7764</Address>
<Phone>021 696 5114</Phone>
<Fax>021 696 6275</Fax>
<Contact></Contact>
<Entered>0</Entered>
<Score>0</Score>
<Email>admin1@neddoman.wcape.school.za</Email>
</Schools>
<Schools>
<Name>Ocean View Sec School</Name>
<Key>076</Key>
<Language>e</Language>
<Address>Hydra Avenue
OCEAN VIEW
7995</Address>
<Phone>021 783 1623</Phone>
<Fax>021 783 3593</Fax>
<Contact></Contact>
<Entered>0</Entered>
<Score>0</Score>
<Email>ovhigh@worldonline.co.za</Email>
</Schools>
<Schools>
<Name>Paarl Boy&amp;#039s High School</Name>
<Key>077</Key>
<Language>e</Language>
<Address>P O Box 11
PAARL
7646</Address>
<Phone>021 872 2875</Phone>
<Fax>021 872 5246</Fax>
<Contact></Contact>
<Entered>0</Entered>
<Score>0</Score>
<Email>info@paarlboyshigh.org.za</Email>
</Schools>
<Schools>
<Name>Paarl Gimnasium </Name>
<Key>078</Key>
<Language>a</Language>
<Address>Posbus 281
PAARL
7620</Address>
<Phone>021 872 1541</Phone>
<Fax>021 872 8654</Fax>
<Contact></Contact>
<Entered>0</Entered>
<Score>0</Score>
<Email>hoof@paarlgim.co.za</Email>
</Schools>
<Schools>
<Name>Paarl Girls&amp;#039 High School</Name>
<Key>079</Key>
<Language>a</Language>
<Address>Posbus 50
PAARL
7622</Address>
<Phone>021 872 1730</Phone>
<Fax>021 872 9102</Fax>
<Contact></Contact>
<Entered>0</Entered>
<Score>0</Score>
<Email>principal@paarlgirlshigh.org.za</Email>
</Schools>
<Schools>
<Name>Parel Vallei High School</Name>
<Key>080</Key>
<Language>e</Language>
<Address>Posbus 400
SOMERSET WES
7129</Address>
<Phone>021 852 1228</Phone>
<Fax>021 852 5005</Fax>
<Contact></Contact>
<Entered>1</Entered>
<Score>0</Score>
<Email>aprinsloo@pvallei.co.za</Email>
</Schools>
<Schools>
<Name>Parklands College of Educ.</Name>
<Key>081</Key>
<Language>e</Language>
<Address>P O Box 11546
BLOUBERGRANDT
7443</Address>
<Phone>021 557 8428</Phone>
<Fax>021 557 8421</Fax>
<Contact></Contact>
<Entered>0</Entered>
<Score>0</Score>
<Email>fdupreez@parklands.co.za</Email>
</Schools>
<Schools>
<Name>Paul Roos Gymnasium</Name>
<Key>082</Key>
<Language>e</Language>
<Address>Suidwal Road
STELLENBOSCH
7600</Address>
<Phone>021 887 0017</Phone>
<Fax>021 883 8461</Fax>
<Contact></Contact>
<Entered>0</Entered>
<Score>0</Score>
<Email></Email>
</Schools>
<Schools>
<Name>Pinelands H S</Name>
<Key>083</Key>
<Language>e</Language>
<Address>Forest Drive
PINELANDS
7405</Address>
<Phone>021 531 7410</Phone>
<Fax>021 531 7415</Fax>
<Contact></Contact>
<Entered>0</Entered>
<Score>0</Score>
<Email>neddy@phs.wcape.school.za</Email>
</Schools>
<Schools>
<Name>Plumstead High School</Name>
<Key>084</Key>
<Language>e</Language>
<Address>Basil Road
PLUMSTEAD
7800</Address>
<Phone>021 761 8066</Phone>
<Fax>021 797 8494</Fax>
<Contact></Contact>
<Entered>0</Entered>
<Score>0</Score>
<Email></Email>
</Schools>
<Schools>
<Name>Portland High School</Name>
<Key>085</Key>
<Language>e</Language>
<Address>C/O Merrydale &amp;
Morgenster Roads
PORTLAND
7785</Address>
<Phone>021 374 4141/2</Phone>
<Fax>021 374 3107</Fax>
<Contact></Contact>
<Entered>1</Entered>
<Score>0</Score>
<Email></Email>
</Schools>
<Schools>
<Name>President H S </Name>
<Key>086</Key>
<Language>a</Language>
<Address>Tygerbergstraaat
VRIJZEE
7460</Address>
<Phone>021 591 5183</Phone>
<Fax>021 591 5181</Fax>
<Contact></Contact>
<Entered>1</Entered>
<Score>0</Score>
<Email>root@hspres.wcape.school.za</Email>
</Schools>
<Schools>
<Name>Proteus Senior Sek Skool</Name>
<Key>087</Key>
<Language>a</Language>
<Address>P O Box 952
REYGERSDAL
ATLANTIS
7352</Address>
<Phone>021 572 6277</Phone>
<Fax>021 572 1540</Fax>
<Contact></Contact>
<Entered>0</Entered>
<Score>0</Score>
<Email>proteus@interkom.co.za</Email>
</Schools>
<Schools>
<Name>Queens Park High School</Name>
<Key>088</Key>
<Language>e</Language>
<Address>Balfour Road
WOODSTOCK
7945</Address>
<Phone>021 448 1997/8</Phone>
<Fax>021 448 3043</Fax>
<Contact></Contact>
<Entered>0</Entered>
<Score>0</Score>
<Email></Email>
</Schools>
<Schools>
<Name>Reddam Coll. Constantia</Name>
<Key>089</Key>
<Language>e</Language>
<Address>Private Bag X14
CONSTANTIA
7848</Address>
<Phone>021 702 2322</Phone>
<Fax>021 702 2366</Fax>
<Contact></Contact>
<Entered>1</Entered>
<Score>0</Score>
<Email>jwilson@reddamh.wcape.school.za</Email>
</Schools>
<Schools>
<Name>Rhenish Girls&amp;#039 H S</Name>
<Key>090</Key>
<Language>e</Language>
<Address>P O Box 87
STELLENBOSCH
7599</Address>
<Phone>021 887 6807</Phone>
<Fax>021 887 8090</Fax>
<Contact></Contact>
<Entered>0</Entered>
<Score>0</Score>
<Email>principal@rhenish.co.za</Email>
</Schools>
